name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Upload node_modules artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - name: Lint code
        run: npm run lint 

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - name: Run tests
        run: echo "Tests running"

  run_build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - name: Build application
        run: echo "Building application..."

  deploy:
    runs-on: ubuntu-latest
    needs: run_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: node_modules

      - name: Deploy application
        run: echo "Deploying application..."
